package com.mozilcode.cloud.db;

import com.mozilcode.cloud.config.CloudConfig;
import jakarta.annotation.PostConstruct;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class DatabaseInitializer {
  private final JdbcTemplate db;
  private final CloudConfig config;
  private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

  public DatabaseInitializer(JdbcTemplate db, CloudConfig config) {
    this.db = db;
    this.config = config;
  }

  @PostConstruct
  public void initialize() {
    migrate();
    seedDefaults();
  }

  private void migrate() {
    db.execute("""
        CREATE TABLE IF NOT EXISTS schema_version (
          version INT PRIMARY KEY,
          applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);
    markVersion(1);
    markVersion(2);
    markVersion(3);

    db.execute("""
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email VARCHAR(255) UNIQUE NOT NULL,
          password_hash VARCHAR(255) NOT NULL,
          role VARCHAR(32) NOT NULL DEFAULT 'user',
          selected_model_id INT DEFAULT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);
    ensureColumn("users", "role", "VARCHAR(32) DEFAULT 'user'");

    db.execute("""
        CREATE TABLE IF NOT EXISTS providers (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          code VARCHAR(64) UNIQUE NOT NULL,
          name VARCHAR(128) NOT NULL,
          protocol VARCHAR(64) NOT NULL DEFAULT 'openai',
          base_url VARCHAR(512) NOT NULL,
          api_key VARCHAR(1024) DEFAULT '',
          is_active SMALLINT DEFAULT 1,
          sort_order INT DEFAULT 0,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);

    db.execute("""
        CREATE TABLE IF NOT EXISTS models (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          display_name VARCHAR(255) NOT NULL,
          provider VARCHAR(64) NOT NULL,
          protocol VARCHAR(64) NOT NULL DEFAULT 'openai',
          base_url VARCHAR(512) NOT NULL DEFAULT '',
          model_id VARCHAR(255) NOT NULL,
          provider_id INT DEFAULT NULL,
          is_active SMALLINT DEFAULT 1,
          sort_order INT DEFAULT 0,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);
    ensureColumn("models", "provider_id", "INT DEFAULT NULL");
    ensureColumn("models", "thinking", "SMALLINT DEFAULT 0");

    db.execute("""
        CREATE TABLE IF NOT EXISTS plans (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          token_quota BIGINT NOT NULL,
          duration_days INT NOT NULL,
          description VARCHAR(255) DEFAULT '',
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """);

    db.execute("""
        CREATE TABLE IF NOT EXISTS redeem_codes (
          code VARCHAR(128) PRIMARY KEY,
          plan_id INT NOT NULL,
          used_by_user_id INT DEFAULT NULL,
          used_at TIMESTAMP DEFAULT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (plan_id) REFERENCES plans(id)
        )
        """);

    db.execute("""
        CREATE TABLE IF NOT EXISTS subscriptions (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INT NOT NULL,
          plan_id INT NOT NULL,
          token_quota BIGINT NOT NULL,
          token_used BIGINT DEFAULT 0,
          expires_at TIMESTAMP NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (user_id) REFERENCES users(id),
          FOREIGN KEY (plan_id) REFERENCES plans(id)
        )
        """);

    db.execute("""
        CREATE TABLE IF NOT EXISTS usage_log (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INT NOT NULL,
          model VARCHAR(255) NOT NULL,
          input_tokens BIGINT DEFAULT 0,
          output_tokens BIGINT DEFAULT 0,
          latency_ms BIGINT DEFAULT 0,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """);

    db.execute("""
        CREATE TABLE IF NOT EXISTS provider_keys (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INT NOT NULL,
          provider VARCHAR(64) NOT NULL,
          label VARCHAR(128) DEFAULT '',
          api_key VARCHAR(1024) NOT NULL,
          is_default SMALLINT DEFAULT 0,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """);
  }

  private void seedDefaults() {
    if (count("providers") == 0) {
      insertProvider("deepseek", "DeepSeek", "https://api.deepseek.com/v1", 0);
      insertProvider("qwen", "通义千问", "https://dashscope.aliyuncs.com/compatible-mode/v1", 1);
      insertProvider("stepfun", "阶跃星辰", "https://api.stepfun.com/step_plan/v1", 2);
      insertProvider("openai", "OpenAI", "https://api.openai.com/v1", 3);
    }

    if (count("models") == 0) {
      seedModel("deepseek-chat", "DeepSeek Chat", "deepseek", "deepseek-chat", 0);
      seedModel("qwen-plus", "Qwen Plus", "qwen", "qwen-plus", 1);
      seedModel("stepfun-flash", "StepFun Flash", "stepfun", "step-3.7-flash", 2);
      seedModel("openai-gpt4o-mini", "GPT-4o Mini", "openai", "gpt-4o-mini", 3);
    } else {
      linkModelsToProviders();
    }

    if (count("plans") == 0) {
      db.update(
          "INSERT INTO plans (name, token_quota, duration_days, description) VALUES (?, ?, ?, ?)",
          "体验套餐", 500_000L, 30, "50 万 token，30 天有效"
      );
      db.update(
          "INSERT INTO plans (name, token_quota, duration_days, description) VALUES (?, ?, ?, ?)",
          "标准套餐", 5_000_000L, 30, "500 万 token，30 天有效"
      );
      db.update(
          "INSERT INTO plans (name, token_quota, duration_days, description) VALUES (?, ?, ?, ?)",
          "专业套餐", 20_000_000L, 30, "2000 万 token，30 天有效"
      );
    }

    if (!config.isProduction() && count("redeem_codes") == 0) {
      db.update("INSERT INTO redeem_codes (code, plan_id) VALUES (?, ?)", "MozilCode-FREE-500K", 1);
      db.update("INSERT INTO redeem_codes (code, plan_id) VALUES (?, ?)", "MozilCode-PRO-5M", 2);
      db.update("INSERT INTO redeem_codes (code, plan_id) VALUES (?, ?)", "MozilCode-MAX-20M", 3);
    }

    seedAdmin();
  }

  private void insertProvider(String code, String name, String baseUrl, int sort) {
    db.update("""
        INSERT INTO providers (code, name, protocol, base_url, api_key, is_active, sort_order)
        VALUES (?, ?, 'openai', ?, '', 1, ?)
        """, code, name, baseUrl, sort);
  }

  private void seedModel(String name, String displayName, String providerCode, String modelId, int sort) {
    List<Map<String, Object>> rows = db.queryForList(
        "SELECT id, protocol, base_url FROM providers WHERE code = ?",
        providerCode
    );
    if (rows.isEmpty()) {
      return;
    }
    Map<String, Object> p = rows.getFirst();
    db.update("""
        INSERT INTO models (name, display_name, provider, protocol, base_url, model_id, provider_id, sort_order)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        name,
        displayName,
        providerCode,
        String.valueOf(p.get("protocol")),
        String.valueOf(p.get("base_url")),
        modelId,
        ((Number) p.get("id")).intValue(),
        sort
    );
  }

  private void linkModelsToProviders() {
    List<Map<String, Object>> providers = db.queryForList("SELECT id, code, protocol, base_url FROM providers");
    for (Map<String, Object> p : providers) {
      db.update("""
          UPDATE models
          SET provider_id = ?, protocol = ?, base_url = ?
          WHERE provider_id IS NULL AND LOWER(provider) = LOWER(?)
          """,
          ((Number) p.get("id")).intValue(),
          String.valueOf(p.get("protocol")),
          String.valueOf(p.get("base_url")),
          String.valueOf(p.get("code"))
      );
    }
  }

  private void seedAdmin() {
    Integer adminCount = db.queryForObject(
        "SELECT COUNT(*) FROM users WHERE role = 'admin'",
        Integer.class
    );
    if (adminCount != null && adminCount > 0) {
      return;
    }
    String email = "admin@mozilcode.local";
    Integer exists = db.queryForObject(
        "SELECT COUNT(*) FROM users WHERE email = ?",
        Integer.class,
        email
    );
    if (exists == null || exists == 0) {
      db.update(
          "INSERT INTO users (email, password_hash, role) VALUES (?, ?, 'admin')",
          email,
          passwordEncoder.encode("admin123")
      );
    } else {
      db.update("UPDATE users SET role = 'admin' WHERE email = ?", email);
    }
  }

  private void markVersion(int version) {
    db.update("""
        INSERT INTO schema_version (version)
        SELECT ? WHERE NOT EXISTS (SELECT 1 FROM schema_version WHERE version = ?)
        """, version, version);
  }

  private void ensureColumn(String table, String column, String definition) {
    try {
      Integer count = db.queryForObject("""
          SELECT COUNT(*) FROM information_schema.columns
          WHERE LOWER(table_name) = LOWER(?) AND LOWER(column_name) = LOWER(?)
          """, Integer.class, table, column);
      if (count != null && count > 0) {
        return;
      }
    } catch (Exception ignored) {
      // try ALTER
    }
    try {
      db.execute("ALTER TABLE " + table + " ADD COLUMN " + column + " " + definition);
    } catch (Exception ignored) {
      // already exists
    }
  }

  private int count(String tableName) {
    Integer count = db.queryForObject("SELECT COUNT(*) FROM " + tableName, Integer.class);
    return count == null ? 0 : count;
  }
}
